/**
 * AgentPhone WebSocket message protocol
 * Shared types between desktop-agent and mobile app.
 *
 * PTY Resize rule: The local terminal (SIGWINCH) is the sole authority for
 * PTY actual size. Mobile clients send MOBILE_VIEWPORT to declare their own
 * render viewport — this never touches the underlying PTY.
 *
 * Auth: challenge-response (HMAC-SHA256). The token itself never travels
 * over the wire; only the HMAC of (token + challenge) is sent.
 */

export enum MessageType {
  // PTY I/O -------------------------------------------------------------------
  /** Desktop → Mobile: raw PTY output bytes (ANSI escape sequences intact) */
  PTY_OUTPUT = 'pty:output',
  /** Mobile → Desktop: keystrokes / text to write into PTY stdin */
  PTY_INPUT = 'pty:input',
  /**
   * Mobile → Desktop: mobile client's render viewport dimensions.
   * DOES NOT change PTY actual size — used only by the mobile xterm.js
   * instance to configure its local rendering columns/rows.
   */
  MOBILE_VIEWPORT = 'mobile:viewport',

  // Auth (challenge-response) -------------------------------------------------
  /** Desktop → Mobile: random challenge bytes (hex-encoded) */
  AUTH_CHALLENGE = 'auth:challenge',
  /** Mobile → Desktop: HMAC-SHA256(token, challenge), hex-encoded */
  AUTH_RESPONSE = 'auth:response',
  /** Desktop → Mobile: authentication succeeded */
  AUTH_OK = 'auth:ok',
  /** Desktop → Mobile: authentication failed — connection will be closed */
  AUTH_FAIL = 'auth:fail',

  // State sync ----------------------------------------------------------------
  /** Desktop → Mobile: terminal history snapshot sent on connect */
  STATE_SNAPSHOT = 'state:snapshot',

  // Control -------------------------------------------------------------------
  /** Mobile → Desktop: send a signal to the Claude Code process */
  CONTROL_SIGNAL = 'control:signal',

  // Heartbeat -----------------------------------------------------------------
  PING = 'ping',
  PONG = 'pong',
}

// ---------------------------------------------------------------------------
// Payload types
// ---------------------------------------------------------------------------

export interface PtyOutputPayload {
  /** Raw ANSI bytes as a UTF-8 string */
  data: string;
}

export interface PtyInputPayload {
  /** Keystrokes / text to write into PTY stdin */
  data: string;
}

export interface MobileViewportPayload {
  /** Number of columns in the mobile xterm.js viewport */
  cols: number;
  /** Number of rows in the mobile xterm.js viewport */
  rows: number;
}

export interface AuthChallengePayload {
  /** Hex-encoded random bytes generated by the Desktop Agent */
  challenge: string;
}

export interface AuthResponsePayload {
  /** hex( HMAC-SHA256(token, challenge) ) */
  hmac: string;
}

export interface StateSnapshotPayload {
  /**
   * Concatenated historical PTY output (raw ANSI).
   * Recipients should reset their xterm.js state before replaying to avoid
   * broken escape sequences from mid-stream truncation.
   */
  history: string;
  /** PTY actual cols at the time of snapshot (local terminal size) */
  cols: number;
  /** PTY actual rows at the time of snapshot (local terminal size) */
  rows: number;
}

export type SignalName = 'SIGINT' | 'SIGTERM' | 'SIGKILL';

export interface ControlSignalPayload {
  signal: SignalName;
}

// ---------------------------------------------------------------------------
// Union message type
// ---------------------------------------------------------------------------

export type MessagePayloadMap = {
  [MessageType.PTY_OUTPUT]: PtyOutputPayload;
  [MessageType.PTY_INPUT]: PtyInputPayload;
  [MessageType.MOBILE_VIEWPORT]: MobileViewportPayload;
  [MessageType.AUTH_CHALLENGE]: AuthChallengePayload;
  [MessageType.AUTH_RESPONSE]: AuthResponsePayload;
  [MessageType.AUTH_OK]: Record<string, never>;
  [MessageType.AUTH_FAIL]: { reason: string };
  [MessageType.STATE_SNAPSHOT]: StateSnapshotPayload;
  [MessageType.CONTROL_SIGNAL]: ControlSignalPayload;
  [MessageType.PING]: Record<string, never>;
  [MessageType.PONG]: Record<string, never>;
};

export interface Message<T extends MessageType = MessageType> {
  type: T;
  timestamp: number;
  payload: MessagePayloadMap[T];
}

/** Type-safe factory for creating protocol messages */
export function createMessage<T extends MessageType>(
  type: T,
  payload: MessagePayloadMap[T],
): Message<T> {
  return { type, timestamp: Date.now(), payload };
}
